### PR TITLE
Clean up files

### PR DESCRIPTION
**Pull request by alextrastero**
Package.json was missing the es2015 preset as a devDependency, also cleaned a few other bits and pieces :pig2::dash:

### CODE REVIEW

**Comment by alextrastero** [comment]
@isaiah :-)

**Comment by isaiah** [comment]
Cool, you are living in the cutting edge now.

Wanna help with the react-materialize repo? Still so many things to do.

**Comment by alextrastero** [comment]
Sure man!

**Comment by alextrastero** [comment]
Do we have a TODO list? add me to the organization :)

**Comment by isaiah** [comment]
Will add you when I am on the computer.

First we need a LOGO, and a better looking website, so we can start doing
some marketing:)

some JavaScript components are not implemented..

Join the gitter room, we can talk there.

**Pull request merged**
